{% set version = "2023.3.0" %}


package:
  name: dask
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/dask/dask-{{ version }}.tar.gz
  sha256: 6773a35efe255e85703574ab5bd27055cfd02536b965e2264f86d2c9128a96cd

build:
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.8
    - dask-core {{ version }}
    - distributed {{ version }}
  run:
    - python >=3.8
    - {{ pin_compatible('dask-core', max_pin='x.x.x') }}
    - {{ pin_compatible('distributed', max_pin='x.x.x') }}
    - cytoolz >=0.8.2
    - lz4
    - numpy >=1.21
    - pandas >=1.3
    - bokeh >=2.4.2,<3
    - jinja2 >=2.10.3

  run_constrained:
    - openssl !=1.1.1e

test:
  imports:
    - dask
    - dask.array
    - dask.bag
    - dask.bytes
    - dask.dataframe
    - dask.dataframe.tseries
    - dask.delayed
    - dask.diagnostics
    - dask.distributed
    - distributed

  commands:
    - dask --version
    - dask info versions

about:
  home: https://dask.org/
  summary: Parallel PyData with Task Scheduling
  license: BSD-3-Clause
  license_file:
    - LICENSE.txt
    - dask/array/NUMPY_LICENSE.txt
  description: |
    Dask is a flexible parallel computing library for analytics.
  doc_url: https://dask.org/
  dev_url: https://github.com/dask/dask

extra:
  recipe-maintainers:
    - charlesbluca
    - alimanfoo
    - jakirkham
    - jcrist
    - martindurant
    - mrocklin
    - pitrou
    - tomaugspurger
    - jrbourbeau
