{% set version = "2024.3.0" %}


package:
  name: dask
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/dask/dask-{{ version }}.tar.gz
  sha256: 04d5e5d66f97ca46f762fce28b595df6df7278a7636b1e5931afcca9b91e6d74

build:
  number: 1
  noarch: python

requirements:
  host:
    - python >=3.9
    - dask-core {{ version }}
    - distributed {{ version }}
  run:
    - python >=3.9
    - {{ pin_compatible('dask-core', max_pin='x.x.x') }}
    - {{ pin_compatible('distributed', max_pin='x.x.x') }}
    - {{ pin_compatible('dask-expr', max_pin='x.x.x') }}
    - cytoolz >=0.11.0
    - lz4 >=4.3.2
    - numpy >=1.21
    - pandas >=1.3
    - dask-expr >=1.0,<1.1
    - bokeh >=2.4.2,!=3.0.*
    - jinja2 >=2.10.3
    - pyarrow >=7.0
    - pyarrow-hotfix

  run_constrained:
    - openssl !=1.1.1e

test:
  imports:
    - dask
    - dask.array
    - dask.bag
    - dask.bytes
    - dask.dataframe
    - dask.dataframe.tseries
    - dask.delayed
    - dask.diagnostics
    - dask.distributed
    - distributed

  commands:
    - dask --version
    - dask info versions

about:
  home: https://dask.org/
  summary: Parallel PyData with Task Scheduling
  license: BSD-3-Clause
  license_file:
    - LICENSE.txt
    - dask/array/NUMPY_LICENSE.txt
  description: |
    Dask is a flexible parallel computing library for analytics.
  doc_url: https://dask.org/
  dev_url: https://github.com/dask/dask

extra:
  recipe-maintainers:
    - charlesbluca
    - alimanfoo
    - jakirkham
    - jcrist
    - martindurant
    - mrocklin
    - pitrou
    - tomaugspurger
    - jrbourbeau
    - fjetter
