{% set version = "1.2.2" %}

package:
  name: dask
  version: "{{ version }}"

source:
  fn: dask-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/d/dask/dask-{{ version }}.tar.gz
  sha256: 5e7876bae2a01b355d1969b73aeafa23310febd8c353163910b73e93dc7e492c

build:
  number: 3
  noarch: python

requirements:
  host:
    - python

  run:
    - python
    - bokeh >=0.13.0
    - cloudpickle >=0.2.1
    - cytoolz >=0.7.3
    - dask-core {{ version }}
    - distributed >=1.28.0
    - numpy >=1.13.0
    - pandas >=0.21.0
    - partd >=0.3.10
    - toolz >=0.7.3

test:
  imports:
    - dask
    - dask.array
    - dask.bag
    - dask.bytes
    - dask.dataframe
    - dask.dataframe.tseries
    - dask.delayed
    - dask.diagnostics
    - dask.distributed
    - distributed

about:
  home: https://dask.org/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Parallel PyData with Task Scheduling'
  description: |
    Dask is a flexible parallel computing library for analytics.
  doc_url: https://dask.org/
  dev_url: https://github.com/dask/dask

extra:
  recipe-maintainers:
    - alimanfoo
    - jakirkham
    - jcrist
    - koverholt
    - martindurant
    - mrocklin
    - pitrou
    - tomaugspurger
    - shoyer
    - jrbourbeau
